# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
        environment:
          APPNAME: datastore
    working_directory: /go/src/github.com/ivanturianytsia/datastore
    steps:
      - checkout
      - type: setup-docker-engine
      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
      - type: shell
        name: Prepare to install Node.js
        command: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - type: shell
        name: Install Node.js
        command: sudo apt-get install -y nodejs
      # - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - type: shell
        name: Install front-end packages
        command: npm install
        working_directory: /go/src/github.com/ivanturianytsia/datastore/client
      - type: shell
        name: Build front-end
        command: npm run build
        working_directory: /go/src/github.com/ivanturianytsia/datastore/client
      - type: shell
        name: Install Go packages
        command: go get -v -d -t ./app
      - type: shell
        name: Test back-end
        command: go test --cover -v ./app/...
      - type: shell
        name: Build back-end
        command: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o bin/${APPNAME}_alpine ./app
      - type: shell
        name: Build docker image
        command: docker build --tag ${APPNAME}:latest --file ./ops/Dockerfile --build-arg APPNAME=${APPNAME} .
      - type: shell
        name: Login into DockerHub
        command: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - type: shell
        name: Tag docker image :latest
        command: docker tag ${APPNAME}:latest ${DOCKER_USERNAME}/${APPNAME}:latest
      - type: shell
        name: Push docker image :latest
        command: docker push ${DOCKER_USERNAME}/${APPNAME}:latest
      - type: shell
        name: Build docker image :hash
        command: docker tag ${APPNAME}:latest ${DOCKER_USERNAME}/${APPNAME}:$(git rev-parse HEAD)
      - type: shell
        name: Push docker image :hash
        command: docker push ${DOCKER_USERNAME}/${APPNAME}:$(git rev-parse HEAD)
