---
version: '3'

services:
  mongo:
    image: "library/mongo:latest"
    networks:
      - backend
  datastore:
    image: "ivanturianytsia/datastore:latest"
    environment:
      - DB=mongo
      - PORT=3000
      - TOKEN_SECRET=THSIISaSedoCkercrettokprodenSecRet
      - TOKEN_EXPIRATION=72
      - ENV=prod
      - DIST_DIR=./client/dist
      - DATA_DIR=./data
      - MAILGUN_DOMAIN=mail.nomidigital.com
      - MAILGUN_KEY=key-a15d635d13c805e172d0dad8e56e36dd
      - MAILGUN_PUBKEY=pubkey-f912855177a172d30bc3614b741e77a2
    ports:
      - "80:3000"
    networks:
      - backend

networks:
  backend:
    driver: overlay
    external: false
